# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31403f3a27ad01585444d8dbacf2ba283bebf3b8a172385e1cac82650bd1443c9340f0e833a14e27771d65b2950475474fa72b69c8354bb9d6e01f31962ad832
  api_key:  'key-eda1d764e17818afceb149b486562ad3'
  domain:   '209.61.151.224'
  username: 'postmaster@sandbox4d6dd856914b44568311bbc1830902d6.mailgun.org'
  password: '4fa007a6c7593fa42c815868588fc801'
test:
  secret_key_base: 0378b70a3d69fc80b5e5f0b0cd942536cbaccef52f626829368116bf3e646ab0392db33da26f44611278b11d263afe39f8f17c9ee7f5f3852ac0633fd094d4fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key:  'key-eda1d764e17818afceb149b486562ad3'
  domain:   '209.61.151.224'
  username: 'postmaster@stockrocker.co.uk'
  password: 'bf39bc49802ed683cb70825aa181ef01'
